insert into categories (id, name, description ) values (1, 'Helianthus ×divariserratus R.W. Long', 'ut odio cras mi pede malesuada');
insert into categories (id, name, description ) values (2, 'Notholithocarpus densiflorus (Hook. & Arn.) P.S. Manos, C.H. Cannon, & S.H. Oh f. attenuatodentatus (J.M. Tucker, Sundahl & D.O. Hall) P.M. McDonald, J.W. Zhang, Senock, & J.W. Wright', 'non mauris morbi non lectus aliquam');
insert into categories (id, name, description ) values (3, 'Platonia esculenta (Arruda) Rickett & Stafleu', 'augue vestibulum ante ipsum primis in faucibus orci luctus');
insert into categories (id, name, description ) values (4, 'Asclepias ovalifolia Decne.', 'eget elit sodales scelerisque mauris sit amet');
insert into categories (id, name, description ) values (5, 'Mangifera caesia Jack ex Wall.', 'pede malesuada in imperdiet et commodo vulputate justo in');
insert into categories (id, name, description ) values (6, 'Sapindus trifoliatus L.', 'nisl duis ac nibh fusce lacus');
insert into categories (id, name, description ) values (7, 'Cassytha filiformis L.', 'facilisi cras non velit nec');
insert into categories (id, name, description ) values (8, 'Gladiolus ×colvillei Sweet', 'suscipit nulla elit ac nulla sed vel enim');
insert into categories (id, name, description ) values (9, 'Potamogeton foliosus Raf. ssp. foliosus', 'rhoncus aliquet pulvinar sed nisl nunc rhoncus dui');
insert into categories (id, name, description ) values (10, 'Porella wataugensis (Sull.) Underw.', 'orci luctus et ultrices posuere cubilia');
insert into categories (id, name, description ) values (11, 'Tortula laevipila (Brid.) Schwägr.', 'cubilia curae duis faucibus accumsan odio curabitur');
insert into categories (id, name, description ) values (12, 'Piloblephis rigida (W. Bartram ex Benth.) Raf.', 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti');
insert into categories (id, name, description ) values (13, 'Gnaphalium exilifolium A. Nelson', 'volutpat erat quisque erat eros viverra eget congue eget');
insert into categories (id, name, description ) values (14, 'Ruellia yucatana (Leonard) Tharp & F.A. Barkley', 'est et tempus semper est quam pharetra magna');
insert into categories (id, name, description ) values (15, 'Asclepias rubra L.', 'a feugiat et eros vestibulum ac est lacinia nisi');
insert into categories (id, name, description ) values (16, 'Caloplaca irrubescens (Arnold) Zahlbr.', 'eget tincidunt eget tempus vel pede morbi');
insert into categories (id, name, description ) values (17, 'Amaranthus bigelovii Uline & Bray', 'mauris viverra diam vitae quam');
insert into categories (id, name, description ) values (18, 'Nemophila menziesii Hook. & Arn. var. menziesii', 'sed vel enim sit amet');
insert into categories (id, name, description ) values (19, 'Daucosma Engelm. & A. Gray ex A. Gray', 'massa tempor convallis nulla neque libero convallis eget');
insert into categories (id, name, description ) values (20, 'Mimulus lewisii Pursh', 'mi integer ac neque duis bibendum morbi');
insert into categories (id, name, description ) values (21, 'Paronychia canadensis (L.) Alph. Wood', 'odio curabitur convallis duis consequat dui');
insert into categories (id, name, description ) values (22, 'Carex biltmoreana Mack.', 'nunc donec quis orci eget orci vehicula condimentum');
insert into categories (id, name, description ) values (23, 'Quercus ×hawkinsiae Sudw.', 'in hac habitasse platea dictumst morbi vestibulum velit id pretium');
insert into categories (id, name, description ) values (24, 'Trichomanes radicans Sw.', 'porttitor pede justo eu massa donec dapibus');
insert into categories (id, name, description ) values (25, 'Robinia hispida L. var. fertilis (Ashe) R.T. Clausen', 'interdum mauris ullamcorper purus sit');
insert into categories (id, name, description ) values (26, 'Polycoccum microstictum (Leight. ex Mudd) Arnold', 'integer pede justo lacinia eget tincidunt eget tempus vel');
insert into categories (id, name, description ) values (27, 'Krigia wrightii (A. Gray) K.L. Chambers ex Kim', 'et tempus semper est quam pharetra magna ac consequat metus');
insert into categories (id, name, description ) values (28, 'Corchorus hirsutus L.', 'facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt');
insert into categories (id, name, description ) values (29, 'Abutilon incanum (Link) Sweet', 'nulla ac enim in tempor turpis nec');
insert into categories (id, name, description ) values (30, 'Erigeron acris L. ssp. kamtschaticus (DC.) H. Hara', 'enim in tempor turpis nec euismod scelerisque');
insert into categories (id, name, description ) values (31, 'Dicerandra cornutissima R.B. Huck', 'parturient montes nascetur ridiculus mus');
insert into categories (id, name, description ) values (32, 'Oenothera cordata J.W. Loudon', 'eu orci mauris lacinia sapien');
insert into categories (id, name, description ) values (33, 'Pyrrocoma linearis (D.D. Keck) Kartesz & Gandhi', 'consequat morbi a ipsum integer a nibh in quis');
insert into categories (id, name, description ) values (34, 'Artemisia abrotanum L.', 'non velit donec diam neque');
insert into categories (id, name, description ) values (35, 'Callirhoe involucrata (Torr. & A. Gray) A. Gray var. involucrata', 'nulla suscipit ligula in lacus curabitur at ipsum');
insert into categories (id, name, description ) values (36, 'Allium gooddingii Ownbey', 'tellus nisi eu orci mauris lacinia sapien quis libero nullam');
insert into categories (id, name, description ) values (37, 'Camissonia heterochroma (S. Watson) P.H. Raven', 'non mauris morbi non lectus aliquam sit');
insert into categories (id, name, description ) values (38, 'Euonymus atropurpureus Jacq. var. atropurpureus', 'neque aenean auctor gravida sem praesent id');
insert into categories (id, name, description ) values (39, 'Hyparrhenia Andersson ex Fourn.', 'mauris lacinia sapien quis libero nullam sit amet turpis');
insert into categories (id, name, description ) values (40, 'Oligomeris Camb.', 'nibh ligula nec sem duis aliquam convallis nunc');
insert into categories (id, name, description ) values (41, 'Gonocarpus chinensis (Lour.) Orchard ssp. verrucosus (Maiden & Betcke) Orchard', 'ultricies eu nibh quisque id justo sit amet sapien dignissim');
insert into categories (id, name, description ) values (42, 'Emorya suaveolens Torr.', 'ante ipsum primis in faucibus orci luctus et ultrices');
insert into categories (id, name, description ) values (43, 'Cirsium parryi (A. Gray) Petr. ssp. mogollonicum C. Schaack & G. Goodwin', 'odio cras mi pede malesuada');
insert into categories (id, name, description ) values (44, 'Bourreria succulenta Jacq.', 'vivamus metus arcu adipiscing molestie hendrerit');
insert into categories (id, name, description ) values (45, 'Arctostaphylos gabilanensis V.T. Parker & M.C. Vasey', 'sagittis sapien cum sociis natoque penatibus et magnis dis parturient');
insert into categories (id, name, description ) values (46, 'Acmella pilosa R.K. Jansen', 'mattis egestas metus aenean fermentum donec ut');
insert into categories (id, name, description ) values (47, 'Brachythecium Schimp.', 'cursus vestibulum proin eu mi nulla ac');
insert into categories (id, name, description ) values (48, 'Acalypha deamii (Weath.) H.E. Ahles', 'sollicitudin ut suscipit a feugiat et eros');
insert into categories (id, name, description ) values (49, 'Deinandra conjugens (D.D. Keck) B.G. Baldw.', 'turpis integer aliquet massa id lobortis convallis tortor');
insert into categories (id, name, description ) values (50, 'Myosotis macrosperma Engelm.', 'arcu sed augue aliquam erat volutpat');
insert into categories (id, name, description ) values (51, 'Arenaria fendleri A. Gray', 'curabitur in libero ut massa');
insert into categories (id, name, description ) values (52, 'Sophora L.', 'tellus in sagittis dui vel nisl duis ac nibh fusce');
insert into categories (id, name, description ) values (53, 'Fragaria ×ananassa (Weston) Duchesne ex Rozier ssp. cuneifolia (Nutt. ex Howell) Staudt (pro nm.)', 'in porttitor pede justo eu massa donec dapibus duis');
insert into categories (id, name, description ) values (54, 'Triodanis texana McVaugh', 'ante ipsum primis in faucibus orci luctus et ultrices');
insert into categories (id, name, description ) values (55, 'Plagiobothrys scouleri (Hook. & Arn.) I.M. Johnst.', 'integer a nibh in quis justo maecenas');
insert into categories (id, name, description ) values (56, 'Pellaea bridgesii Hook.', 'at nunc commodo placerat praesent');
insert into categories (id, name, description ) values (57, 'Lonicera subspicata Hook. & Arn. var. denudata Rehder', 'duis bibendum morbi non quam nec');
insert into categories (id, name, description ) values (58, 'Sambucus nigra L.', 'platea dictumst etiam faucibus cursus');
insert into categories (id, name, description ) values (59, 'Lewisia leeana (Porter) B.L. Rob.', 'libero ut massa volutpat convallis morbi odio odio');
insert into categories (id, name, description ) values (60, 'Calibrachoa parviflora (Juss.) D''Arcy', 'orci mauris lacinia sapien quis libero nullam sit');
insert into categories (id, name, description ) values (61, 'Costus guanaiensis Rusby var. macrostrobilus (K. Schum.) Maas', 'sit amet eleifend pede libero quis orci nullam molestie');
insert into categories (id, name, description ) values (62, 'Mentzelia tiehmii N.H. Holmgren & P.K. Holmgren', 'eleifend luctus ultricies eu nibh');
insert into categories (id, name, description ) values (63, 'Pyrrocoma racemosa (Nutt.) Torr. & A. Gray', 'massa tempor convallis nulla neque libero convallis eget');
insert into categories (id, name, description ) values (64, 'Thelypodium laciniatum (Hook.) Endl. ex Walp.', 'interdum eu tincidunt in leo');
insert into categories (id, name, description ) values (65, 'Paronychia setacea Torr. & A. Gray', 'augue vestibulum rutrum rutrum neque aenean');
insert into categories (id, name, description ) values (66, 'Matelea arizonica (A. Gray) Shinners', 'consequat morbi a ipsum integer');
insert into categories (id, name, description ) values (67, 'Vaccinium pallidum Aiton', 'pretium iaculis diam erat fermentum justo nec condimentum neque');
insert into categories (id, name, description ) values (68, 'Bryoerythrophyllum columbianum (F.J. Herm. & E. Lawton) R.H. Zander', 'morbi sem mauris laoreet ut');
insert into categories (id, name, description ) values (69, 'Psychotria maricaensis Urb.', 'nulla tempus vivamus in felis eu sapien cursus vestibulum proin');
insert into categories (id, name, description ) values (70, 'Stipulicida setacea Michx.', 'at vulputate vitae nisl aenean lectus pellentesque eget nunc');
insert into categories (id, name, description ) values (71, 'Gayophytum eriospermum Coville', 'rhoncus sed vestibulum sit amet cursus id turpis');
insert into categories (id, name, description ) values (72, 'Clematis campaniflora Brot.', 'at turpis donec posuere metus');
insert into categories (id, name, description ) values (73, 'Senna racemosa (Mill.) Irwin & Barneby [excluded]', 'fusce congue diam id ornare imperdiet sapien urna pretium');
insert into categories (id, name, description ) values (74, 'Schiedea nuttallii Hook.', 'praesent id massa id nisl venenatis');
insert into categories (id, name, description ) values (75, 'Hexastylis heterophylla (Ashe) Small', 'rhoncus aliquam lacus morbi quis tortor');
insert into categories (id, name, description ) values (76, 'Fritillaria ojaiensis Davidson', 'eros vestibulum ac est lacinia nisi');
insert into categories (id, name, description ) values (77, 'Angelonia angustifolia Benth.', 'ante ipsum primis in faucibus');
insert into categories (id, name, description ) values (78, 'Rhynchospora caduca Elliott', 'tortor risus dapibus augue vel accumsan tellus nisi');
insert into categories (id, name, description ) values (79, 'Lepidium jaredii Brandegee ssp. album Hoover', 'eros elementum pellentesque quisque porta volutpat erat quisque erat');
insert into categories (id, name, description ) values (80, 'Sorghum bicolor (L.) Moench ssp. bicolor', 'integer pede justo lacinia eget tincidunt eget tempus vel pede');
insert into categories (id, name, description ) values (81, 'Eriogonum cithariforme S. Watson var. agninum (Greene) Reveal', 'congue risus semper porta volutpat quam pede lobortis');
insert into categories (id, name, description ) values (82, 'Descurainia sophioides (Fisch. ex Hook.) O.E. Schulz', 'adipiscing elit proin risus praesent lectus');
insert into categories (id, name, description ) values (83, 'Crepis runcinata (James) Torr. & A. Gray ssp. imbricata Babc. & Stebbins', 'non mattis pulvinar nulla pede ullamcorper augue');
insert into categories (id, name, description ) values (84, 'Arthonia chiodectella Nyl.', 'cras pellentesque volutpat dui maecenas tristique est et');
insert into categories (id, name, description ) values (85, 'Bidens conjuncta Sherff', 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh');
insert into categories (id, name, description ) values (86, 'Dryptodon Brid.', 'sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie');
insert into categories (id, name, description ) values (87, 'Rosa obtusiuscula Rydb., nom. inq.', 'massa id lobortis convallis tortor risus dapibus augue');
insert into categories (id, name, description ) values (88, 'Rhizoplaca glaucophana (Nyl. ex Hasse) W.A. Weber', 'elementum pellentesque quisque porta volutpat erat quisque erat eros viverra');
insert into categories (id, name, description ) values (89, 'Cicuta maculata L. var. bolanderi (S. Watson) G. Mulligan', 'in tempor turpis nec euismod scelerisque');
insert into categories (id, name, description ) values (90, 'Pinguicula macroceras Link', 'diam erat fermentum justo nec condimentum neque sapien placerat');
insert into categories (id, name, description ) values (91, 'Abronia villosa S. Watson var. villosa', 'viverra eget congue eget semper');
insert into categories (id, name, description ) values (92, 'Bigelowia nudata (Michx.) DC.', 'in congue etiam justo etiam pretium iaculis');
insert into categories (id, name, description ) values (93, 'Mirabilis gigantea (Standl.) Shinners', 'aliquet pulvinar sed nisl nunc rhoncus dui vel');
insert into categories (id, name, description ) values (94, 'Cladidium bolanderi (Tuck.) B.D. Ryan', 'in felis donec semper sapien a libero nam dui proin');
insert into categories (id, name, description ) values (95, 'Anemone nemorosa L.', 'vitae consectetuer eget rutrum at lorem');
insert into categories (id, name, description ) values (96, 'Cladonia furcata (Huds.) Schrad. ssp. subrangiformis (Scriba ex Sandst.) Pisut', 'et ultrices posuere cubilia curae nulla dapibus dolor vel');
insert into categories (id, name, description ) values (97, 'Acanthospermum Schrank', 'praesent lectus vestibulum quam sapien');
insert into categories (id, name, description ) values (98, 'Schoenus tendo Banks & Sol. ex Hook. f.', 'ante vestibulum ante ipsum primis in faucibus');
insert into categories (id, name, description ) values (99, 'Acacia drummondii Lindl.', 'hac habitasse platea dictumst maecenas ut massa quis augue');
insert into categories (id, name, description ) values (100, 'Hexastylis shuttleworthii (Britten & Baker f.) Small var. harperi Gaddy', 'orci nullam molestie nibh in lectus');
