insert into categories (name, description ) values ('Adventure', 'metus arcu adipiscing molestie hendrerit at vulputate');
insert into categories (name, description ) values ('Action', 'congue etiam justo etiam pretium iaculis justo in hac');
insert into categories (name, description ) values ('Animation', 'ut tellus nulla ut erat id');
insert into categories (name, description ) values ('Comedy', 'nulla ut erat id mauris vulputate elementum');
insert into categories (name, description ) values ('Drama', 'turpis elementum ligula vehicula consequat morbi a');
insert into categories (name, description ) values ('Documentary', 'orci luctus et ultrices posuere cubilia');
insert into categories (name, description ) values ('Film-Noir', 'sapien placerat ante nulla justo');
insert into categories (name, description ) values ('Musical', 'nulla integer pede justo lacinia');
insert into categories (name, description ) values ('Mystery', 'id mauris vulputate elementum nullam varius');
insert into categories (name, description ) values ('Horror', 'praesent lectus vestibulum quam sapien');
insert into categories (name, description ) values ('IMAX', 'nonummy integer non velit donec');
insert into categories (name, description ) values ('Romance', 'at turpis a pede posuere nonummy integer non');
insert into categories (name, description ) values ('Thriller', 'magna at nunc commodo placerat praesent blandit nam nulla integer');
insert into categories (name, description ) values ('Featured', 'vel sem sed sagittis nam congue risus semper porta volutpat');
