insert into categories (name, description ) values ('Comedy|Drama|Romance', 'ultrices mattis odio donec vitae');
insert into categories (name, description ) values ('Comedy', 'porta volutpat quam pede lobortis ligula sit amet eleifend pede');
insert into categories (name, description ) values ('Action|Adventure|Animation', 'ligula in lacus curabitur at ipsum ac');
insert into categories (name, description ) values ('Horror|Thriller|IMAX', 'sed lacus morbi sem mauris');
insert into categories (name, description ) values ('Comedy|Drama|Romance', 'id ligula suspendisse ornare consequat lectus in est risus auctor');
insert into categories (name, description ) values ('Comedy', 'felis eu sapien cursus vestibulum proin eu mi nulla');
insert into categories (name, description ) values ('(no genres listed)', 'aenean fermentum donec ut mauris eget');
insert into categories (name, description ) values ('Comedy|Drama', 'blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing');
insert into categories (name, description ) values ('Comedy|Drama|Romance', 'morbi porttitor lorem id ligula suspendisse ornare consequat');
insert into categories (name, description ) values ('Action|Adventure|Drama|Romance', 'id turpis integer aliquet massa id lobortis convallis');
insert into categories (name, description ) values ('Comedy|Drama|Musical', 'sapien cum sociis natoque penatibus et magnis');
insert into categories (name, description ) values ('Comedy', 'consectetuer adipiscing elit proin risus praesent');
insert into categories (name, description ) values ('(no genres listed)', 'aliquam quis turpis eget elit');
insert into categories (name, description ) values ('Comedy', 'et ultrices posuere cubilia curae nulla dapibus dolor');
insert into categories (name, description ) values ('Animation|Drama', 'blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing');
insert into categories (name, description ) values ('Thriller', 'in leo maecenas pulvinar lobortis est phasellus sit amet');
insert into categories (name, description ) values ('Documentary', 'tincidunt eu felis fusce posuere felis sed');
insert into categories (name, description ) values ('Adventure|Drama|Western', 'et ultrices posuere cubilia curae nulla dapibus dolor');
insert into categories (name, description ) values ('Horror|Mystery', 'justo in hac habitasse platea dictumst etiam');
insert into categories (name, description ) values ('Drama|Film-Noir|Mystery|Romance', 'sit amet diam in magna bibendum imperdiet nullam orci pede');
