insert into reviews (id, order_id, item_id, user_id, rating, message) values (1, 68, 743, 752, 3, 'nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (2, 89, 583, 673, 5, 'at ipsum ac tellus semper interdum mauris ullamcorper purus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (3, 14, 345, 911, 5, 'magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (4, 57, 536, 914, 2, 'libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (5, 12, 881, 798, 4, 'nibh in lectus pellentesque at nulla suspendisse potenti cras');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (6, 32, 174, 639, 1, 'congue diam id ornare imperdiet sapien urna pretium');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (7, 85, 87, 7, 4, 'porttitor id consequat in consequat ut nulla sed');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (8, 91, 723, 685, 1, 'nisi nam ultrices libero non mattis pulvinar nulla pede');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (9, 68, 48, 826, 4, 'odio condimentum id luctus nec molestie sed justo pellentesque viverra');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (10, 52, 93, 772, 5, 'erat curabitur gravida nisi at nibh in hac');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (11, 1, 930, 517, 5, 'cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (12, 53, 374, 816, 2, 'justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (13, 5, 535, 929, 2, 'pellentesque eget nunc donec quis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (14, 73, 49, 555, 4, 'gravida nisi at nibh in hac habitasse');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (15, 20, 312, 712, 1, 'nulla tellus in sagittis dui vel');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (16, 4, 22, 129, 1, 'id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (17, 97, 733, 815, 2, 'pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (18, 50, 256, 805, 1, 'etiam vel augue vestibulum rutrum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (19, 77, 870, 46, 2, 'in leo maecenas pulvinar lobortis est phasellus sit amet');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (20, 72, 571, 886, 2, 'vestibulum velit id pretium iaculis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (21, 70, 246, 919, 1, 'dictumst etiam faucibus cursus urna ut tellus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (22, 54, 111, 669, 5, 'amet lobortis sapien sapien non mi integer ac neque');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (23, 4, 341, 372, 1, 'congue elementum in hac habitasse platea dictumst morbi vestibulum velit');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (24, 93, 870, 76, 1, 'eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (25, 87, 632, 702, 2, 'augue luctus tincidunt nulla mollis molestie');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (26, 77, 57, 403, 4, 'integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (27, 65, 875, 800, 4, 'pede malesuada in imperdiet et commodo vulputate justo in');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (28, 54, 672, 403, 5, 'non quam nec dui luctus rutrum nulla tellus in sagittis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (29, 35, 843, 552, 5, 'ac consequat metus sapien ut nunc vestibulum ante');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (30, 76, 128, 32, 1, 'habitasse platea dictumst maecenas ut massa quis augue luctus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (31, 14, 795, 557, 2, 'porttitor pede justo eu massa donec dapibus duis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (32, 3, 130, 984, 4, 'sit amet turpis elementum ligula');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (33, 33, 894, 394, 2, 'nec molestie sed justo pellentesque viverra pede');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (34, 88, 810, 90, 2, 'ligula nec sem duis aliquam convallis nunc proin at turpis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (35, 73, 815, 535, 2, 'sagittis nam congue risus semper porta volutpat quam pede');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (36, 77, 479, 363, 3, 'ligula vehicula consequat morbi a ipsum integer a nibh in');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (37, 37, 746, 109, 4, 'in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (38, 53, 725, 933, 5, 'vestibulum velit id pretium iaculis diam erat fermentum justo nec');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (39, 34, 952, 934, 3, 'fusce lacus purus aliquet at');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (40, 95, 883, 100, 4, 'mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (41, 1, 438, 214, 5, 'a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (42, 35, 404, 989, 3, 'velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (43, 63, 615, 608, 2, 'elementum in hac habitasse platea dictumst morbi vestibulum velit id');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (44, 19, 802, 205, 1, 'penatibus et magnis dis parturient montes nascetur ridiculus mus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (45, 89, 142, 592, 2, 'interdum in ante vestibulum ante ipsum primis in faucibus orci');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (46, 82, 138, 864, 3, 'ligula suspendisse ornare consequat lectus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (47, 66, 468, 129, 5, 'vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (48, 12, 164, 355, 3, 'vulputate elementum nullam varius nulla facilisi cras non velit nec');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (49, 22, 507, 755, 5, 'aenean auctor gravida sem praesent id');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (50, 4, 885, 447, 3, 'tristique in tempus sit amet sem fusce consequat');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (51, 23, 729, 77, 5, 'consectetuer eget rutrum at lorem integer tincidunt ante vel');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (52, 12, 622, 691, 2, 'vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (53, 73, 622, 785, 5, 'tortor risus dapibus augue vel');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (54, 78, 831, 524, 4, 'curabitur at ipsum ac tellus semper interdum mauris ullamcorper');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (55, 53, 572, 672, 2, 'eu massa donec dapibus duis at velit eu est congue elementum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (56, 61, 603, 175, 4, 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (57, 17, 418, 659, 1, 'faucibus orci luctus et ultrices posuere cubilia');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (58, 80, 615, 859, 3, 'et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (59, 49, 176, 230, 3, 'erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (60, 69, 276, 567, 3, 'sit amet justo morbi ut odio cras mi pede malesuada in');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (61, 21, 817, 697, 4, 'quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (62, 83, 581, 51, 1, 'sem duis aliquam convallis nunc proin at');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (63, 78, 622, 166, 3, 'vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (64, 53, 580, 223, 5, 'vulputate vitae nisl aenean lectus pellentesque eget');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (65, 35, 397, 139, 4, 'iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (66, 74, 356, 445, 1, 'volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (67, 4, 375, 501, 3, 'amet justo morbi ut odio cras mi pede malesuada');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (68, 91, 881, 97, 1, 'nisi vulputate nonummy maecenas tincidunt lacus at velit');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (69, 51, 15, 845, 5, 'odio donec vitae nisi nam');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (70, 24, 474, 829, 3, 'amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (71, 50, 504, 935, 3, 'proin at turpis a pede posuere nonummy integer non velit donec diam');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (72, 66, 216, 708, 4, 'praesent lectus vestibulum quam sapien varius ut blandit non interdum in');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (73, 55, 610, 433, 5, 'porttitor lorem id ligula suspendisse ornare consequat lectus in');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (74, 93, 505, 598, 4, 'bibendum imperdiet nullam orci pede venenatis non sodales sed');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (75, 46, 335, 404, 4, 'tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (76, 61, 842, 818, 5, 'luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (77, 70, 284, 107, 4, 'eu est congue elementum in hac habitasse');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (78, 18, 424, 753, 5, 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (79, 17, 897, 488, 4, 'vestibulum aliquet ultrices erat tortor');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (80, 69, 577, 642, 4, 'eget rutrum at lorem integer tincidunt ante');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (81, 46, 623, 526, 1, 'volutpat convallis morbi odio odio elementum eu interdum eu tincidunt');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (82, 50, 689, 528, 3, 'orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (83, 31, 9, 61, 4, 'lacinia aenean sit amet justo morbi ut odio cras mi pede');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (84, 48, 319, 467, 2, 'maecenas rhoncus aliquam lacus morbi quis tortor id');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (85, 38, 78, 120, 3, 'bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (86, 56, 774, 797, 3, 'vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (87, 57, 919, 714, 5, 'lobortis vel dapibus at diam nam tristique');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (88, 71, 355, 213, 4, 'erat eros viverra eget congue eget semper rutrum nulla nunc');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (89, 30, 649, 882, 3, 'ipsum integer a nibh in quis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (90, 1, 174, 710, 1, 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (91, 10, 664, 477, 2, 'luctus ultricies eu nibh quisque id justo sit amet sapien dignissim');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (92, 10, 645, 851, 3, 'nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (93, 22, 10, 417, 3, 'tellus semper interdum mauris ullamcorper purus sit amet');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (94, 19, 418, 889, 3, 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (95, 69, 421, 562, 5, 'nec euismod scelerisque quam turpis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (96, 61, 698, 738, 2, 'sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (97, 80, 782, 464, 5, 'orci luctus et ultrices posuere cubilia curae donec pharetra');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (98, 90, 732, 784, 1, 'molestie hendrerit at vulputate vitae nisl aenean lectus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (99, 35, 583, 828, 5, 'nam congue risus semper porta volutpat');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (100, 16, 906, 831, 1, 'amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (101, 73, 398, 648, 2, 'venenatis turpis enim blandit mi in porttitor pede justo eu massa');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (102, 15, 458, 162, 5, 'vel est donec odio justo');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (103, 63, 770, 851, 4, 'ut massa volutpat convallis morbi');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (104, 91, 498, 554, 1, 'vestibulum proin eu mi nulla ac enim in tempor turpis nec');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (105, 99, 255, 453, 4, 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (106, 83, 414, 332, 4, 'elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (107, 5, 984, 10, 4, 'id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (108, 13, 96, 671, 3, 'suspendisse potenti nullam porttitor lacus at');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (109, 51, 558, 552, 5, 'pellentesque viverra pede ac diam');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (110, 86, 494, 465, 4, 'nisl aenean lectus pellentesque eget nunc donec quis orci eget orci');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (111, 97, 703, 571, 5, 'lectus pellentesque at nulla suspendisse potenti cras in purus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (112, 50, 191, 122, 2, 'rhoncus dui vel sem sed sagittis nam');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (113, 66, 299, 202, 2, 'maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (114, 24, 912, 543, 1, 'sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (115, 10, 962, 784, 3, 'eu nibh quisque id justo sit amet sapien dignissim');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (116, 29, 734, 429, 3, 'dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (117, 1, 551, 285, 3, 'sem sed sagittis nam congue');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (118, 82, 593, 20, 1, 'erat eros viverra eget congue eget semper rutrum nulla');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (119, 49, 764, 307, 3, 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (120, 9, 44, 970, 3, 'ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (121, 13, 792, 915, 5, 'pede lobortis ligula sit amet eleifend pede libero');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (122, 97, 735, 546, 1, 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (123, 9, 505, 956, 2, 'semper sapien a libero nam dui proin leo odio');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (124, 42, 753, 513, 5, 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (125, 1, 28, 564, 3, 'fermentum justo nec condimentum neque sapien placerat ante nulla justo');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (126, 56, 339, 479, 3, 'ac enim in tempor turpis nec euismod scelerisque quam');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (127, 3, 983, 818, 1, 'lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (128, 13, 365, 763, 3, 'id nisl venenatis lacinia aenean sit amet justo morbi ut');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (129, 18, 356, 915, 3, 'suspendisse ornare consequat lectus in est risus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (130, 44, 134, 136, 2, 'metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (131, 90, 599, 499, 3, 'lobortis vel dapibus at diam nam tristique tortor eu pede');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (132, 61, 853, 279, 5, 'diam in magna bibendum imperdiet nullam orci pede venenatis non sodales');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (133, 90, 864, 177, 4, 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (134, 43, 647, 446, 4, 'justo aliquam quis turpis eget elit');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (135, 99, 360, 836, 3, 'justo in hac habitasse platea dictumst etiam');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (136, 13, 492, 494, 3, 'justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (137, 14, 965, 189, 5, 'duis mattis egestas metus aenean fermentum donec ut mauris eget massa');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (138, 84, 47, 930, 1, 'ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (139, 30, 441, 947, 3, 'libero nam dui proin leo odio porttitor id consequat in consequat ut nulla');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (140, 86, 575, 447, 2, 'odio condimentum id luctus nec molestie sed justo pellentesque viverra pede');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (141, 19, 112, 374, 2, 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (142, 42, 634, 11, 1, 'velit donec diam neque vestibulum eget vulputate ut');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (143, 12, 598, 672, 4, 'morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (144, 38, 95, 525, 2, 'eu interdum eu tincidunt in leo');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (145, 28, 934, 536, 1, 'magna ac consequat metus sapien ut nunc vestibulum ante ipsum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (146, 29, 396, 917, 2, 'mauris enim leo rhoncus sed vestibulum sit amet cursus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (147, 27, 483, 338, 5, 'non mi integer ac neque duis bibendum morbi non');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (148, 6, 106, 625, 3, 'vivamus in felis eu sapien cursus vestibulum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (149, 89, 591, 800, 2, 'velit eu est congue elementum in hac habitasse platea');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (150, 70, 79, 988, 3, 'velit eu est congue elementum in hac habitasse');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (151, 43, 290, 324, 1, 'aliquam erat volutpat in congue etiam justo etiam pretium iaculis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (152, 22, 358, 149, 4, 'posuere metus vitae ipsum aliquam non mauris');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (153, 40, 106, 433, 4, 'duis bibendum morbi non quam');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (154, 29, 872, 126, 1, 'id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (155, 60, 433, 926, 1, 'volutpat erat quisque erat eros viverra');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (156, 14, 202, 667, 5, 'suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (157, 16, 923, 165, 5, 'morbi non lectus aliquam sit');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (158, 15, 429, 168, 5, 'a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (159, 51, 963, 934, 1, 'proin at turpis a pede');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (160, 41, 975, 358, 4, 'proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (161, 1, 812, 555, 2, 'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (162, 8, 50, 924, 2, 'pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (163, 5, 793, 375, 4, 'dictumst etiam faucibus cursus urna');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (164, 31, 693, 991, 5, 'orci luctus et ultrices posuere cubilia');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (165, 38, 337, 137, 4, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (166, 60, 608, 761, 4, 'consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (167, 49, 940, 114, 3, 'justo maecenas rhoncus aliquam lacus morbi quis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (168, 45, 263, 875, 3, 'in felis donec semper sapien a libero nam dui proin leo odio porttitor');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (169, 55, 153, 525, 5, 'orci eget orci vehicula condimentum curabitur in libero');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (170, 16, 128, 737, 1, 'habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (171, 33, 985, 258, 5, 'consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (172, 88, 264, 113, 2, 'bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (173, 37, 232, 539, 4, 'ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (174, 8, 921, 903, 3, 'id ligula suspendisse ornare consequat lectus in est risus auctor');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (175, 84, 536, 394, 2, 'mi integer ac neque duis bibendum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (176, 78, 228, 137, 2, 'ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (177, 53, 878, 525, 5, 'ante ipsum primis in faucibus orci');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (178, 57, 156, 702, 4, 'in faucibus orci luctus et ultrices');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (179, 67, 27, 549, 3, 'venenatis turpis enim blandit mi in porttitor');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (180, 90, 755, 776, 5, 'non pretium quis lectus suspendisse potenti in');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (181, 8, 337, 193, 4, 'nisi eu orci mauris lacinia sapien quis libero');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (182, 70, 706, 107, 1, 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (183, 51, 886, 665, 1, 'semper rutrum nulla nunc purus phasellus in felis donec semper sapien a');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (184, 24, 653, 668, 4, 'et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (185, 61, 743, 613, 1, 'in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (186, 48, 535, 667, 1, 'a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (187, 61, 626, 482, 5, 'sit amet sapien dignissim vestibulum vestibulum ante');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (188, 50, 500, 308, 3, 'ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (189, 71, 837, 311, 5, 'amet cursus id turpis integer aliquet');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (190, 54, 500, 667, 4, 'at nulla suspendisse potenti cras in purus eu magna vulputate');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (191, 30, 897, 299, 3, 'non sodales sed tincidunt eu felis fusce posuere');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (192, 50, 331, 439, 4, 'ac est lacinia nisi venenatis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (193, 21, 755, 75, 4, 'nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (194, 8, 128, 557, 1, 'mauris sit amet eros suspendisse accumsan tortor');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (195, 94, 414, 57, 4, 'volutpat sapien arcu sed augue aliquam erat volutpat in congue');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (196, 70, 687, 675, 4, 'massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (197, 45, 586, 901, 5, 'in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (198, 84, 210, 942, 1, 'sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (199, 35, 713, 455, 5, 'justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (200, 78, 960, 997, 4, 'justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (201, 28, 791, 528, 2, 'nulla integer pede justo lacinia eget tincidunt');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (202, 75, 414, 200, 4, 'magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (203, 67, 284, 246, 1, 'eros elementum pellentesque quisque porta volutpat');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (204, 32, 787, 648, 2, 'est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (205, 44, 925, 359, 3, 'at velit eu est congue elementum in hac habitasse');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (206, 73, 155, 422, 5, 'pellentesque quisque porta volutpat erat quisque erat eros viverra');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (207, 97, 531, 906, 2, 'primis in faucibus orci luctus et ultrices');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (208, 36, 940, 743, 2, 'tempor turpis nec euismod scelerisque quam turpis adipiscing');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (209, 25, 184, 734, 4, 'vestibulum ante ipsum primis in faucibus orci');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (210, 35, 982, 721, 3, 'vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (211, 58, 846, 79, 4, 'primis in faucibus orci luctus et ultrices');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (212, 52, 788, 177, 5, 'justo etiam pretium iaculis justo in');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (213, 19, 390, 206, 5, 'eu interdum eu tincidunt in leo');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (214, 84, 225, 753, 5, 'parturient montes nascetur ridiculus mus etiam vel augue vestibulum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (215, 16, 772, 130, 3, 'aliquam augue quam sollicitudin vitae consectetuer eget');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (216, 58, 115, 985, 3, 'etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (217, 91, 128, 347, 3, 'sem mauris laoreet ut rhoncus aliquet pulvinar sed');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (218, 19, 768, 698, 3, 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (219, 63, 553, 494, 3, 'integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (220, 19, 344, 962, 5, 'odio odio elementum eu interdum eu tincidunt in leo');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (221, 46, 122, 79, 3, 'venenatis lacinia aenean sit amet');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (222, 94, 694, 667, 5, 'nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (223, 67, 67, 523, 4, 'sit amet nulla quisque arcu libero rutrum ac lobortis vel');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (224, 67, 811, 83, 4, 'vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (225, 42, 805, 710, 2, 'in felis eu sapien cursus vestibulum proin');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (226, 38, 204, 57, 2, 'condimentum id luctus nec molestie sed justo');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (227, 2, 370, 758, 1, 'elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (228, 76, 260, 71, 2, 'sem sed sagittis nam congue risus semper');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (229, 9, 627, 254, 1, 'luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (230, 79, 590, 805, 1, 'duis aliquam convallis nunc proin at turpis a pede');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (231, 92, 271, 217, 1, 'in lacus curabitur at ipsum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (232, 93, 165, 90, 1, 'luctus tincidunt nulla mollis molestie lorem quisque ut');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (233, 29, 273, 448, 4, 'feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (234, 24, 429, 303, 2, 'nam nulla integer pede justo lacinia eget tincidunt');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (235, 14, 116, 446, 5, 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (236, 80, 321, 438, 1, 'quis augue luctus tincidunt nulla mollis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (237, 67, 652, 553, 5, 'rutrum nulla tellus in sagittis dui vel nisl');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (238, 32, 773, 496, 4, 'eget semper rutrum nulla nunc purus phasellus in felis donec semper');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (239, 92, 609, 461, 2, 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (240, 30, 345, 544, 1, 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (241, 88, 274, 659, 5, 'augue vel accumsan tellus nisi eu orci');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (242, 85, 733, 440, 5, 'erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (243, 89, 552, 622, 1, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (244, 15, 56, 90, 4, 'montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (245, 88, 534, 876, 1, 'est lacinia nisi venenatis tristique fusce congue diam id ornare');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (246, 87, 113, 468, 3, 'odio in hac habitasse platea dictumst maecenas ut massa quis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (247, 14, 862, 278, 2, 'ac nibh fusce lacus purus aliquet at');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (248, 21, 562, 729, 1, 'ultrices posuere cubilia curae nulla dapibus dolor');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (249, 65, 665, 510, 2, 'dui luctus rutrum nulla tellus in sagittis dui');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (250, 73, 320, 174, 4, 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (251, 19, 827, 324, 3, 'volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (252, 92, 481, 2, 4, 'duis ac nibh fusce lacus purus aliquet at feugiat non pretium');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (253, 90, 439, 822, 4, 'sed sagittis nam congue risus semper porta volutpat quam pede lobortis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (254, 42, 582, 469, 3, 'ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (255, 94, 276, 909, 3, 'non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (256, 76, 828, 637, 1, 'ridiculus mus etiam vel augue vestibulum rutrum rutrum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (257, 27, 229, 475, 5, 'pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (258, 97, 970, 878, 3, 'platea dictumst maecenas ut massa quis augue luctus tincidunt');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (259, 28, 566, 598, 2, 'purus phasellus in felis donec semper sapien a libero nam dui proin');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (260, 72, 598, 100, 3, 'at nibh in hac habitasse platea dictumst aliquam augue');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (261, 16, 811, 11, 5, 'a ipsum integer a nibh in quis justo maecenas');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (262, 28, 584, 14, 1, 'facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (263, 43, 272, 356, 1, 'viverra dapibus nulla suscipit ligula in lacus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (264, 61, 156, 85, 5, 'vel augue vestibulum ante ipsum primis in faucibus orci luctus et');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (265, 18, 829, 375, 5, 'neque sapien placerat ante nulla justo aliquam quis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (266, 34, 967, 791, 2, 'in lectus pellentesque at nulla suspendisse potenti cras in purus eu');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (267, 37, 403, 869, 5, 'felis donec semper sapien a libero nam dui proin leo');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (268, 18, 165, 839, 5, 'diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (269, 35, 281, 141, 2, 'elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (270, 31, 96, 191, 1, 'tortor duis mattis egestas metus aenean fermentum donec ut mauris');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (271, 93, 205, 382, 1, 'dui luctus rutrum nulla tellus in sagittis dui vel');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (272, 52, 626, 929, 1, 'nulla tellus in sagittis dui');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (273, 36, 214, 292, 1, 'duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (274, 25, 936, 296, 2, 'praesent blandit lacinia erat vestibulum sed magna at nunc commodo');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (275, 61, 30, 756, 5, 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (276, 51, 671, 788, 4, 'nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (277, 57, 739, 930, 1, 'nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (278, 88, 766, 49, 5, 'neque aenean auctor gravida sem praesent id massa id');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (279, 70, 164, 495, 5, 'ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (280, 6, 285, 921, 1, 'a ipsum integer a nibh');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (281, 61, 847, 727, 3, 'sed nisl nunc rhoncus dui vel sem sed sagittis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (282, 97, 991, 685, 5, 'justo sollicitudin ut suscipit a');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (283, 5, 578, 355, 1, 'pellentesque ultrices phasellus id sapien in');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (284, 78, 428, 190, 1, 'sollicitudin ut suscipit a feugiat et');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (285, 52, 349, 634, 1, 'sit amet sem fusce consequat');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (286, 25, 392, 386, 2, 'scelerisque quam turpis adipiscing lorem vitae mattis nibh');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (287, 39, 691, 954, 4, 'quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (288, 39, 561, 600, 5, 'dui proin leo odio porttitor id consequat in consequat ut');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (289, 97, 917, 377, 5, 'in ante vestibulum ante ipsum primis in faucibus orci');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (290, 99, 138, 144, 3, 'eu nibh quisque id justo sit');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (291, 61, 819, 869, 4, 'sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (292, 7, 696, 689, 1, 'eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (293, 67, 963, 69, 3, 'eu magna vulputate luctus cum sociis natoque penatibus et magnis dis');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (294, 28, 457, 597, 4, 'pellentesque volutpat dui maecenas tristique est et tempus semper est');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (295, 42, 586, 494, 2, 'nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (296, 49, 290, 932, 4, 'proin interdum mauris non ligula');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (297, 5, 288, 31, 5, 'potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (298, 75, 891, 423, 1, 'est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (299, 10, 761, 84, 2, 'gravida sem praesent id massa id');
insert into reviews (id, order_id, item_id, user_id, rating, message) values (300, 81, 930, 356, 1, 'non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam');
