insert into reviews (order_id, item_id, user_id, rating, message) values (1, 8, 2, 1, 'maecenas tincidunt lacus at velit vivamus vel nulla eget eros');
insert into reviews (order_id, item_id, user_id, rating, message) values (3, 3, 11, 3, 'integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla');
insert into reviews (order_id, item_id, user_id, rating, message) values (10, 1, 14, 1, 'adipiscing lorem vitae mattis nibh ligula nec');
insert into reviews (order_id, item_id, user_id, rating, message) values (9, 9, 6, 3, 'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus');
insert into reviews (order_id, item_id, user_id, rating, message) values (3, 14, 12, 1, 'posuere nonummy integer non velit donec diam neque');
insert into reviews (order_id, item_id, user_id, rating, message) values (2, 3, 4, 5, 'cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius');
insert into reviews (order_id, item_id, user_id, rating, message) values (8, 11, 2, 1, 'ut at dolor quis odio consequat');
insert into reviews (order_id, item_id, user_id, rating, message) values (6, 17, 9, 2, 'augue aliquam erat volutpat in congue');
insert into reviews (order_id, item_id, user_id, rating, message) values (10, 3, 10, 1, 'proin interdum mauris non ligula');
insert into reviews (order_id, item_id, user_id, rating, message) values (6, 3, 3, 5, 'neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit');
insert into reviews (order_id, item_id, user_id, rating, message) values (2, 1, 20, 4, 'ligula nec sem duis aliquam convallis nunc proin at turpis a pede');
insert into reviews (order_id, item_id, user_id, rating, message) values (6, 13, 10, 2, 'praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit');
insert into reviews (order_id, item_id, user_id, rating, message) values (2, 4, 6, 4, 'lorem quisque ut erat curabitur gravida nisi at nibh');
insert into reviews (order_id, item_id, user_id, rating, message) values (5, 4, 20, 4, 'lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum');
insert into reviews (order_id, item_id, user_id, rating, message) values (5, 6, 11, 3, 'nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum');
insert into reviews (order_id, item_id, user_id, rating, message) values (4, 7, 13, 5, 'volutpat eleifend donec ut dolor morbi');
insert into reviews (order_id, item_id, user_id, rating, message) values (2, 16, 2, 4, 'ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus');
insert into reviews (order_id, item_id, user_id, rating, message) values (3, 11, 12, 4, 'consequat in consequat ut nulla sed accumsan felis');
insert into reviews (order_id, item_id, user_id, rating, message) values (3, 19, 19, 2, 'at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum');
insert into reviews (order_id, item_id, user_id, rating, message) values (3, 7, 8, 4, 'nullam sit amet turpis elementum ligula vehicula consequat morbi');
